/* tcc-java */
import IdText from '../../misc/utils/IdText';

export default class OrgaoConstantes {
	static getList() {
		return OrgaoConstantes.list;
	}
}
OrgaoConstantes._26201_COLEGIO_PEDRO_II = 1;
OrgaoConstantes._21000_COMANDO_DA_AERONAUTICA = 2;
OrgaoConstantes._45205_FUND_INST_BRASIL_GEOG_E_ESTATISTICA = 3;
OrgaoConstantes._36205_FUNDACAO_NACIONAL_DE_SAUDE = 4;
OrgaoConstantes._26277_FUNDACAO_UNIV_FEDERAL_DE_OURO_PRETO = 5;
OrgaoConstantes._26274_FUNDACAO_UNIV_FEDERAL_DE_UBERLANDIA = 6;
OrgaoConstantes._40803_GOVERNO_DO_EX_TERRITORIO_DE_RONDONIA = 7;
OrgaoConstantes._40804_GOVERNO_DO_EX_TERRITORIO_DE_RORAIMA = 8;
OrgaoConstantes._40801_GOVERNO_DO_EX_TERRITORIO_DO_AMAPA = 9;
OrgaoConstantes._40701_INST_BR_MEIO_AMB_REC_NAT_RENOVAVEIS = 10;
OrgaoConstantes._26403_INSTITUTO_FEDERAL_DO_AMAZONAS = 11;
OrgaoConstantes._30204_INSTITUTO_NAC_DA_PROPRIEDADE_INDUSTRIAL = 12;
OrgaoConstantes._57202_INSTITUTO_NACIONAL_DE_SEGURO_SOCIAL = 13;
OrgaoConstantes._40108_MINISTERIO_DA_CIENCIA_E_TECNOLOGIA = 14;
OrgaoConstantes._17000_MINISTERIO_DA_FAZENDA = 15;
OrgaoConstantes._25000_MINISTERIO_DA_SAUDE = 16;
OrgaoConstantes._49000_MINISTERIO_DOS_TRANSPORTES = 17;
OrgaoConstantes._40805_ORGAO_40805 = 18;
OrgaoConstantes._26269_UNIVERSIDADE_DO_RIO_DE_JANEIRO = 19;
OrgaoConstantes._26239_UNIVERSIDADE_FEDERAL_DO_PARA = 20;
OrgaoConstantes._26248_UNIVERSIDADE_FEDERAL_RURAL_DE_PERNAMBUCO = 21;
OrgaoConstantes._13000_MINIST_DA_AGRICULTURA_PECUARIA_E_ABAST = 22;
OrgaoConstantes._15000_MINISTERIO_DA_EDUCACAO = 23;
OrgaoConstantes._16000_COMANDO_DO_EXERCITO = 24;
OrgaoConstantes.list = [
	new IdText(OrgaoConstantes._26201_COLEGIO_PEDRO_II, "26201 - COLEGIO PEDRO II"),
	new IdText(OrgaoConstantes._21000_COMANDO_DA_AERONAUTICA, "21000 - COMANDO DA AERONAUTICA"),
	new IdText(OrgaoConstantes._45205_FUND_INST_BRASIL_GEOG_E_ESTATISTICA, "45205 - FUND, INST, BRASIL, GEOG, E ESTATISTICA"),
	new IdText(OrgaoConstantes._36205_FUNDACAO_NACIONAL_DE_SAUDE, "36205 - FUNDACAO NACIONAL DE SAUDE"),
	new IdText(OrgaoConstantes._26277_FUNDACAO_UNIV_FEDERAL_DE_OURO_PRETO, "26277 - FUNDACAO UNIV, FEDERAL DE OURO PRETO"),
	new IdText(OrgaoConstantes._26274_FUNDACAO_UNIV_FEDERAL_DE_UBERLANDIA, "26274 - FUNDACAO UNIV, FEDERAL DE UBERLANDIA"),
	new IdText(OrgaoConstantes._40803_GOVERNO_DO_EX_TERRITORIO_DE_RONDONIA, "40803 - GOVERNO DO EX-TERRITORIO DE RONDONIA"),
	new IdText(OrgaoConstantes._40804_GOVERNO_DO_EX_TERRITORIO_DE_RORAIMA, "40804 - GOVERNO DO EX-TERRITORIO DE RORAIMA"),
	new IdText(OrgaoConstantes._40801_GOVERNO_DO_EX_TERRITORIO_DO_AMAPA, "40801 - GOVERNO DO EX-TERRITORIO DO AMAPA"),
	new IdText(OrgaoConstantes._40701_INST_BR_MEIO_AMB_REC_NAT_RENOVAVEIS, "40701 - INST, BR, MEIO AMB, REC, NAT, RENOVAVEIS"),
	new IdText(OrgaoConstantes._26403_INSTITUTO_FEDERAL_DO_AMAZONAS, "26403 - INSTITUTO FEDERAL DO AMAZONAS"),
	new IdText(OrgaoConstantes._30204_INSTITUTO_NAC_DA_PROPRIEDADE_INDUSTRIAL, "30204 - INSTITUTO NAC, DA PROPRIEDADE INDUSTRIAL"),
	new IdText(OrgaoConstantes._57202_INSTITUTO_NACIONAL_DE_SEGURO_SOCIAL, "57202 - INSTITUTO NACIONAL DE SEGURO SOCIAL"),
	new IdText(OrgaoConstantes._40108_MINISTERIO_DA_CIENCIA_E_TECNOLOGIA, "40108 - MINISTERIO DA CIENCIA E TECNOLOGIA"),
	new IdText(OrgaoConstantes._17000_MINISTERIO_DA_FAZENDA, "17000 - MINISTERIO DA FAZENDA"),
	new IdText(OrgaoConstantes._25000_MINISTERIO_DA_SAUDE, "25000 - MINISTERIO DA SAUDE"),
	new IdText(OrgaoConstantes._49000_MINISTERIO_DOS_TRANSPORTES, "49000 - MINISTERIO DOS TRANSPORTES"),
	new IdText(OrgaoConstantes._40805_ORGAO_40805, "40805 - ORGAO 40805"),
	new IdText(OrgaoConstantes._26269_UNIVERSIDADE_DO_RIO_DE_JANEIRO, "26269 - UNIVERSIDADE DO RIO DE JANEIRO"),
	new IdText(OrgaoConstantes._26239_UNIVERSIDADE_FEDERAL_DO_PARA, "26239 - UNIVERSIDADE FEDERAL DO PARA"),
	new IdText(OrgaoConstantes._26248_UNIVERSIDADE_FEDERAL_RURAL_DE_PERNAMBUCO, "26248 - UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO"),
	new IdText(OrgaoConstantes._13000_MINIST_DA_AGRICULTURA_PECUARIA_E_ABAST, "13000 - MINIST.DA AGRICULTURA,PECUARIA E ABAST."),
	new IdText(OrgaoConstantes._15000_MINISTERIO_DA_EDUCACAO, "15000 - MINISTERIO DA EDUCACAO"),
	new IdText(OrgaoConstantes._16000_COMANDO_DO_EXERCITO, "16000 - COMANDO DO EXERCITO")
];
